export default interface LibType {
  Alert: any
  InputBase: any
  Button: any
  Checkbox: any
  Collapsible: any
  Empty: any
  Form: any
  Image: any
  Input: any
  Label: any
  Popper: any
  Portal: any
  Radio: any
  ScrollArea: any
  Separator: any
  Slot: any
  Switch: any
  Typography: any
  VisuallyHidden: any
  createColors: any
  THEME_DEFAULT: any
  THEME_DARK: any
  styled: any
  useCallbackRef: any
  useClickOutside: any
  useCollapse: any
  useImageLoadingStatus: any
  useIsInViewport: any
  useScrollLock: any
  useToggle: any
  css: any
  keyframes: any
  globalCss: any
  getCssText: any
  applyTheme: any
  createTheme: any
  darkTheme: any
  defaultTheme: any
}
